name: Lobbybow
main: pgn.lobby.bow.main
version: 0.1a
author: [Aussie_Jhawking]
commands:
   bow:
      description: Donator Bow.
      permission: pcg.bow
      permission-message: §cThis is a donator perk!